import { RadarField } from "./types";

export const radarFields = [
  {
    key: "xgFor",
    label: "得点期待値",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "shootFor",
    label: "シュート",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "onTargetFor",
    label: "枠内シュート",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "pkShootFor",
    label: "PKによるシュート",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "passFor",
    label: "パス",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "crossFor",
    label: "クロス",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "directFkFor",
    label: "直接ＦＫ",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "indirectFkFor",
    label: "間接ＦＫ",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "cornerKickFor",
    label: "ＣＫ",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "throwInFor",
    label: "スローイン",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "dribbleFor",
    label: "ドリブル",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "tackleFor",
    label: "タックル",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "clearFor",
    label: "クリア",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "interceptFor",
    label: "インターセプト",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "offsideFor",
    label: "オフサイド",
    category: "attack",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "yellowCardFor",
    label: "警告",
    category: "attack",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "redCardFor",
    label: "退場",
    category: "attack",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "entryAtk3rdFor",
    label: "ATK3rd進入",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "entryPenaltyAreaFor",
    label: "PA進入",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "distanceFor",
    label: "総移動距離",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "sprintFor",
    label: "スプリント",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "attackCountFor",
    label: "攻撃回数",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "chanceCreationRateFor",
    label: "チャンス構築率",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "shootSuccessRateFor",
    label: "シュート成功率",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "passSuccessRateFor",
    label: "パス成功率",
    category: "attack",
    higherIsBetter: true,
    default: true,
  },
  {
    key: "crossSuccessRateFor",
    label: "クロス成功率",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "throwInSuccessRateFor",
    label: "スローイン成功率",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "dribbleSuccessRateFor",
    label: "ドリブル成功率",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "tackleSuccessRateFor",
    label: "タックル成功率",
    category: "attack",
    higherIsBetter: true,
    default: false,
  },
  {
    key: "possession",
    label: "ボール保持率",
    category: "",
    default: false,
    higherIsBetter: true,
  },
  {
    key: "acc_time",
    label: "プレイタイム",
    category: "",
    default: false,
    higherIsBetter: true,
  },
  {
    key: "xgAgainst",
    label: "失点期待値",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "shootAgainst",
    label: "被シュート",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "onTargetAgainst",
    label: "被枠内シュート",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "pkShootAgainst",
    label: "被PKによるシュート",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "passAgainst",
    label: "被パス",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "crossAgainst",
    label: "被クロス",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "directFkAgainst",
    label: "被直接ＦＫ",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "indirectFkAgainst",
    label: "被間接ＦＫ",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "cornerKickAgainst",
    label: "被ＣＫ",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "throwInAgainst",
    label: "被スローイン",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "dribbleAgainst",
    label: "被ドリブル",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "tackleAgainst",
    label: "被タックル",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "clearAgainst",
    label: "被クリア",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "interceptAgainst",
    label: "被インターセプト",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "offsideAgainst",
    label: "被オフサイド",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "yellowCardAgainst",
    label: "被警告",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "redCardAgainst",
    label: "被退場",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "entryAtk3rdAgainst",
    label: "被ATK3rd進入",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "entryPenaltyAreaAgainst",
    label: "被PA進入",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "distanceAgainst",
    label: "被総移動距離",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "sprintAgainst",
    label: "被スプリント",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "attackCountAgainst",
    label: "被攻撃回数",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "chanceCreationRateAgainst",
    label: "被チャンス構築率",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "shootSuccessRateAgainst",
    label: "被シュート成功率",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "passSuccessRateAgainst",
    label: "被パス成功率",
    category: "defense",
    higherIsBetter: false,
    default: true,
  },
  {
    key: "crossSuccessRateAgainst",
    label: "被クロス成功率",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "throwInSuccessRateAgainst",
    label: "被スローイン成功率",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "dribbleSuccessRateAgainst",
    label: "被ドリブル成功率",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
  {
    key: "tackleSuccessRateAgainst",
    label: "被タックル成功率",
    category: "defense",
    higherIsBetter: false,
    default: false,
  },
] as const satisfies readonly RadarField[];
