import express from "express";

import competitionStage from "./competition-stage.js";
import competition from "./competition.js";
import country from "./country.js";
import formation from "./formation.js";
import injury from "./injury.js";
import matchEventType from "./match-event-type.js";
import matchFormat from "./match-format.js";
import match from "./match.js";
import nationalCallup from "./national-callup.js";
import nationalMatchSeries from "./national-match-series.js";
import playerAppearance from "./player-appearance.js";
import playerMatchEventLog from "./player-match-event-log.js";
import playerRegistrationHistory from "./player-registration-history.js";
import playerRegistration from "./player-registration.js";
import player from "./player.js";
import refereeAppearance from "./referee-appearance.js";
import referee from "./referee.js";
import season from "./season.js";
import stadium from "./stadium.js";
import staffAppearance from "./staff-appearance.js";
import staffMatchEventLog from "./staff-match-event-log.js";
import staffRegistrationHistory from "./staff-registration-history.js";
import staffRegistration from "./staff-registration.js";
import staff from "./staff.js";
import statsL from "./stats-l.js";
import teamCompetitionSeason from "./team-competition-season.js";
import teamMatchFormation from "./team-match-formation.js";
import team from "./team.js";
import transfer from "./transfer.js";

const router = express.Router();

router.use(competitionStage);
router.use(competition);
router.use(country);
router.use(formation);
router.use(injury);
router.use(matchEventType);
router.use(matchFormat);
router.use(match);
router.use(nationalCallup);
router.use(nationalMatchSeries);
router.use(playerAppearance);
router.use(playerMatchEventLog);
router.use(playerRegistrationHistory);
router.use(playerRegistration);
router.use(player);
router.use(refereeAppearance);
router.use(referee);
router.use(season);
router.use(stadium);
router.use(staffAppearance);
router.use(staffMatchEventLog);
router.use(staffRegistrationHistory);
router.use(staffRegistration);
router.use(staff);
router.use(statsL);
router.use(teamCompetitionSeason);
router.use(teamMatchFormation);
router.use(team);
router.use(transfer);

export default router;
