import { UIFieldDefinition } from "../../types/field";

export const competitionStage: UIFieldDefinition[] = [
  {
    key: "competition",
    filterKey: "competition.name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "season",
    filterKey: "season.name",
    label: "シーズン",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "stage_type",
    label: "ステージタイプ",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "round_number",
    label: "ラウンド (1=1 回戦, 2=2 回戦)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "leg",
    label: "2試合合計制など (1=1st, 2=2nd)",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "order",
    label: "並び順",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "parent_stage",
    label: "親要素",
    type: "select",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
  {
    key: "notes",
    label: "メモ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
];
