import { UIFieldDefinition } from "../../types/field";
import { CompetitionStageGet } from "../../types/models/competition-stage";
import { ColumnType } from "../../types/table";

export const competitionStage: UIFieldDefinition<CompetitionStageGet>[] = [
  {
    key: "competition",
    field: "competition",
    filterKey: "competition.name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "season",
    field: "season",
    filterKey: "season.name",
    label: "シーズン",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "stage_type",
    field: "stage_type",
    label: "ステージタイプ",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "name",
    field: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "round_number",
    field: "round_number",
    label: "ラウンド (1=1 回戦, 2=2 回戦)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "leg",
    field: "leg",
    label: "2試合合計制など (1=1st, 2=2nd)",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "order",
    field: "order",
    label: "並び順",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "parent_stage",
    field: "parent_stage",
    label: "親要素",
    type: "select",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "notes",
    field: "notes",
    label: "メモ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
