import { UIFieldDefinition } from "../../types/field";

export const competition: UIFieldDefinition[] = [
  {
    key: "name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "abbr",
    label: "略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "country",
    filterKey: "country.name",
    label: "国",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "competition_type",
    label: "大会規模（club, national, other)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "category",
    label: "大会タイプ（league, cup, po, friendly, qualification)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "level",
    label: "大会レベル（◯部, リーグカップ, 入れ替え, 等)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "age_group",
    label: "年代",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "official_match",
    label: "公式戦",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
  {
    key: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
];
