import { UIFieldDefinition } from "../../types/field";
import { CompetitionGet } from "../../types/models/competition";
import { ColumnType } from "../../types/table";

export const competition: UIFieldDefinition<CompetitionGet>[] = [
  {
    key: "name",
    field: "name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "abbr",
    field: "abbr",
    label: "略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "en_name",
    field: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "country",
    field: "country",
    width: "70px",
    filterKey: "country.name",
    label: "国",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "competition_type",
    field: "competition_type",
    width: "90px",
    label: "大会規模（club, national, other)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "category",
    field: "category",
    width: "100px",
    label: "大会タイプ（league, cup, po, friendly, qualification)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "level",
    field: "level",
    label: "大会レベル（◯部, リーグカップ, 入れ替え, 等)",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "age_group",
    field: "age_group",
    width: "70px",
    label: "年代",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "official_match",
    field: "official_match",
    label: "公式戦",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "transferurl",
    field: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "sofaurl",
    field: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
