import { UIFieldDefinition } from "../../types/field";
import { CountryGet } from "../../types/models/country";
import { ColumnType } from "../../types/table";

export const country: UIFieldDefinition<CountryGet>[] = [
  {
    key: "name",
    field: "name",
    label: "国名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "en_name",
    field: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "iso3",
    field: "iso3",
    label: "コード",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "fifa_code",
    field: "fifa_code",
    label: "FIFAコード",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "area",
    field: "area",
    label: "地域",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "district",
    field: "district",
    label: "詳細地域",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "confederation",
    field: "confederation",
    label: "所属地域協会",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "sub_confederation",
    field: "sub_confederation",
    label: "所属詳細地域協会",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "established_year",
    field: "established_year",
    label: "協会成立年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "fifa_member_year",
    field: "fifa_member_year",
    label: "FIFA 加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "association_member_year",
    field: "association_member_year",
    label: "地域協会加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "district_member_year",
    field: "district_member_year",
    label: "詳細地域協会加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "old_id",
    field: "old_id",
    label: "旧ID",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
