import { UIFieldDefinition } from "../../types/field";

export const country: UIFieldDefinition[] = [
  {
    key: "name",
    label: "国名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "iso3",
    label: "コード",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "fifa_code",
    label: "FIFAコード",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "area",
    label: "地域",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "district",
    label: "詳細地域",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "confederation",
    label: "所属地域協会",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "sub_confederation",
    label: "所属詳細地域協会",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "established_year",
    label: "協会成立年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "fifa_member_year",
    label: "FIFA 加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "association_member_year",
    label: "地域協会加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "district_member_year",
    label: "詳細地域協会加入年",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
];
