import { UIFieldDefinition } from "../../types/field";

export const match: UIFieldDefinition[] = [
  {
    key: "competition",
    label: "大会",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "competition_stage",
    label: "大会ステージ",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "season",
    label: "シーズン",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "home_team",
    label: "ホームチーム",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "away_team",
    label: "アウェイチーム",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "match_format",
    label: "試合フォーマット",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "stadium",
    label: "スタジアム",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "play_time",
    label: "プレイ時間",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "date",
    label: "日付",
    type: "datetime-local",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "audience",
    label: "観客数",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },

  {
    key: "home_goal",
    label: "ホーム得点",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "away_goal",
    label: "アウェイ得点",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "home_pk_goal",
    label: "ホームPK得点",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "away_pk_goal",
    label: "アウェイPK得点",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "result",
    label: "試合結果",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "match_week",
    label: "節",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "weather",
    label: "天気",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "temperature",
    label: "気温",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "humidity",
    label: "湿度",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
  {
    key: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
  {
    key: "urls",
    label: "URLS",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
  {
    key: "old_id",
    label: "旧ID",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
];
