import { UIFieldDefinition } from "../../types/field";
import { MatchGet } from "../../types/models/match";
import { ColumnType } from "../../types/table";

export const match: UIFieldDefinition<MatchGet>[] = [
  {
    key: "name",
    field: "name",
    filterKey: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "competition",
    field: "competition",
    filterKey: "competition.name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "competition_stage",
    field: "competition_stage",
    filterKey: "competition_stage.name",
    label: "大会ステージ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "season",
    field: "season",
    filterKey: "season.name",
    label: "シーズン",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "home_team",
    field: "home_team",
    filterKey: "home_team.team",
    label: "ホームチーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "away_team",
    field: "away_team",
    filterKey: "away_team.team",
    label: "アウェイチーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "match_format",
    field: "match_format",
    label: "試合フォーマット",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "stadium",
    field: "stadium",
    filterKey: "stadium.name",
    label: "スタジアム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "play_time",
    field: "play_time",
    label: "プレイ時間",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "date",
    field: "date",
    label: "日付",
    type: "datetime-local",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "audience",
    field: "audience",
    label: "観客数",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "result-string",
    label: "結果",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
    getData: (d: MatchGet) => {
      if (d.home_goal !== undefined && d.away_goal !== undefined) {
        // ゴール数がある場合
        const score =
          d.home_goal !== undefined && d.away_goal !== undefined
            ? `${d.home_goal}-${d.away_goal}`
            : "";

        // PKがある場合
        const pk =
          d.home_pk_goal !== undefined && d.away_pk_goal !== undefined
            ? `(${d.home_pk_goal}PK${d.away_pk_goal})`
            : "";

        return score + pk;
      }

      return "試合前";
    },
  },
  {
    key: "home_goal",
    field: "home_goal",
    label: "ホーム得点",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "away_goal",
    field: "away_goal",
    label: "アウェイ得点",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "home_pk_goal",
    field: "home_pk_goal",
    label: "ホームPK得点",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "away_pk_goal",
    field: "away_pk_goal",
    label: "アウェイPK得点",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "result",
    field: "result",
    label: "試合結果",
    type: "select",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "match_week",
    field: "match_week",
    width: "80px",
    label: "節",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "weather",
    field: "weather",
    label: "天気",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "temperature",
    field: "temperature",
    label: "気温",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "humidity",
    field: "humidity",
    label: "湿度",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "transferurl",
    field: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "sofaurl",
    field: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "urls",
    field: "urls",
    label: "URLS",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "old_id",
    field: "old_id",
    label: "旧ID",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
