import { UIFieldDefinition } from "../../types/field";
import { MatchFormatGet } from "../../types/models/match-format";
import { ColumnType } from "../../types/table";
import { periodField } from "../../utils/displayField/periodField";

export const matchFormat: UIFieldDefinition<MatchFormatGet>[] = [
  {
    key: "name",
    field: "name",
    width: "150px",
    label: "試合フォーマット",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "1st",
    getData: (d: MatchFormatGet) => periodField(d, "前半"),
    label: "前半",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "2nd",
    getData: (d: MatchFormatGet) => periodField(d, "後半"),
    label: "後半",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "1stEX",
    getData: (d: MatchFormatGet) => periodField(d, "延長前半"),
    label: "延長前半",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "2ndEX",
    getData: (d: MatchFormatGet) => periodField(d, "延長後半"),
    label: "延長後半",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "3rdhalf",
    getData: (d: MatchFormatGet) => periodField(d, "3部"),
    label: "3部",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "4thhalf",
    getData: (d: MatchFormatGet) => periodField(d, "4部"),
    label: "4部",
    type: "string",
    width: "80px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "PK",
    getData: (d: MatchFormatGet) => periodField(d, "PK"),
    label: "PK",
    type: "string",
    width: "60px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
  {
    key: "GB",
    getData: (d: MatchFormatGet) => periodField(d, "ゴールデンボール"),
    label: "GB",
    type: "string",
    width: "60px",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.CUSTOM,
  },
];
