import { FieldDefinition } from "../../types/field";

export const nationalCallUp: FieldDefinition[] = [
  {
    key: "series",
    label: "代表試合シリーズ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "player",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "joined_at",
    label: "活動開始日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "left_at",
    label: "解散日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "number",
    label: "背番号",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "position",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "is_captain",
    label: "キャプテン",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "is_overage",
    label: "オーバーエイジ",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "is_backup",
    label: "バックアップ",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "is_training_partner",
    label: "トレーニングパートナー",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "is_additional_call",
    label: "追加招集",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "status",
    label: "招集状況",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "left_reason",
    label: "離脱理由",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
];
