import { UIFieldDefinition } from "../../types/field";
import { NationalCallupGet } from "../../types/models/national-callup";
import { ColumnType } from "../../types/table";

export const nationalCallUp: UIFieldDefinition<NationalCallupGet>[] = [
  {
    key: "series",
    field: "series",
    width: "250px",
    filterKey: "series.name",
    label: "代表試合シリーズ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "player",
    field: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "team",
    field: "team",
    filterKey: "team.team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "joined_at",
    field: "joined_at",
    label: "活動開始日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "left_at",
    field: "left_at",
    label: "解散日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "number",
    field: "number",
    width: "100px",
    label: "背番号",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "position_group",
    field: "position_group",
    width: "100px",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "is_captain",
    field: "is_captain",
    label: "キャプテン",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "is_overage",
    field: "is_overage",
    label: "オーバーエイジ",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "is_backup",
    field: "is_backup",
    label: "バックアップ",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "is_training_partner",
    field: "is_training_partner",
    label: "トレーニングパートナー",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "is_additional_call",
    field: "is_additional_call",
    label: "追加招集",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "status",
    field: "status",
    width: "100px",
    label: "招集状況",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "left_reason",
    field: "left_reason",
    label: "離脱理由",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
