import { UIFieldDefinition } from "../../types/field";
import { NationalMatchSeriesGet } from "../../types/models/national-match-series";
import { ColumnType } from "../../types/table";

export const nationalMatchSeries: UIFieldDefinition<NationalMatchSeriesGet>[] =
  [
    {
      key: "name",
      width: "250px",
      field: "name",
      label: "代表試合シリーズ",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "abbr",
      field: "abbr",
      label: "略称",
      type: "string",
      filterable: false,
      sortable: false,
      displayOnDetail: true,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "country",
      width: "100px",
      field: "country",
      filterKey: "country.name",
      label: "国",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "age_group",
      width: "100px",
      field: "age_group",
      label: "年代・種別",
      type: "select",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "matchs",
      field: "matchs",
      label: "試合",
      type: "string",
      filterable: false,
      sortable: false,
      displayOnDetail: false,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "joined_at",
      field: "joined_at",
      label: "活動開始日",
      type: "Date",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "left_at",
      field: "left_at",
      label: "解散日",
      type: "Date",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "urls",
      field: "urls",
      label: "URL",
      type: "string",
      filterable: false,
      sortable: false,
      displayOnDetail: true,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
  ];
