import { UIFieldDefinition } from "../../types/field";
import { PlayerMatchEventLogGet } from "../../types/models/player-match-event-log";
import { ColumnType } from "../../types/table";

export const playerMatchEventLog: UIFieldDefinition<PlayerMatchEventLogGet>[] =
  [
    {
      key: "match",
      field: "match",
      filterKey: "match",
      label: "試合",
      type: "select",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "team",
      field: "team",
      filterKey: "team.team",
      label: "チーム",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "match_event_type",
      field: "match_event_type",
      filterKey: "match_event_type.name",
      label: "イベントタイプ",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "player",
      field: "player",
      filterKey: "player.name",
      label: "選手",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "time",
      field: "time",
      label: "時間",
      type: "number",
      filterable: false,
      sortable: false,
      displayOnDetail: false,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "add_time",
      field: "add_time",
      label: "追加タイム",
      type: "number",
      filterable: false,
      sortable: false,
      displayOnDetail: false,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "special_time",
      field: "special_time",
      label: "特別タイム",
      type: "select",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "period_label",
      field: "period_label",
      label: "前後半",
      type: "select",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "time_name",
      field: "time_name",
      label: "時間",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: true,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "order",
      field: "order",
      label: "順番",
      type: "string",
      filterable: true,
      sortable: true,
      displayOnDetail: true,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
    {
      key: "unique_key",
      field: "unique_key",
      label: "ユニークキー",
      type: "string",
      filterable: false,
      sortable: false,
      displayOnDetail: false,
      displayOnTable: false,
      getValueType: ColumnType.FIELD,
    },
  ];
