import { UIFieldDefinition } from "../../types/field";
import { PlayerAppearanceGet } from "../../types/models/player-appearance";
import { ColumnType } from "../../types/table";

export const playerAppearance: UIFieldDefinition<PlayerAppearanceGet>[] = [
  {
    key: "match",
    field: "match",
    filterKey: "match",
    label: "試合",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "player",
    field: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "team",
    field: "team",
    filterKey: "team.team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "number",
    field: "number",
    label: "背番号",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "play_status",
    field: "play_status",
    label: "ステータス",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "position",
    field: "position",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "time",
    field: "time",
    label: "プレイ時間",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
];
