import { UIFieldDefinition } from "../../types/field";

export const playerRegistration: UIFieldDefinition[] = [
  {
    key: "date",
    label: "日付",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "season",
    filterKey: "season.name",
    label: "シーズン",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "competition",
    filterKey: "competition.name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "team",
    filterKey: "team.team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "number",
    label: "背番号",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "position_group",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "registration_type",
    label: "登録・抹消",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "height",
    label: "身長",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "weight",
    label: "体重",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "homegrown",
    label: "ホームグロウン",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "registration_status",
    label: "登録状況",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "isTypeTwo",
    label: "2種登録",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "isSpecialDesignation",
    label: "特別指定",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "note",
    label: "メモ",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
];
