import { UIFieldDefinition } from "../../types/field";
import { RefereeGet } from "../../types/models/referee";
import { ColumnType } from "../../types/table";

export const referee: UIFieldDefinition<RefereeGet>[] = [
  {
    key: "name",
    field: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "en_name",
    field: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "normalized_en_name",
    field: "normalized_en_name",
    label: "正規化英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "dob",
    field: "dob",
    label: "生年月日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "pob",
    field: "pob",
    label: "出身地",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "citizenship",
    field: "citizenship",
    label: "国籍",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "player",
    field: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "transferurl",
    field: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "sofaurl",
    field: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "old_id",
    field: "old_id",
    label: "旧ID",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
];
