import { UIFieldDefinition } from "../../types/field";

export const stadium: UIFieldDefinition[] = [
  {
    key: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "abbr",
    label: "略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "en_name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "alt_names",
    label: "別名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "alt_abbrs",
    label: "別略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "alt_en_names",
    label: "別英語名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "country",
    label: "国",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "transferurl",
    label: "transferurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
  {
    key: "sofaurl",
    label: "sofaurl",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
];
