import { UIFieldDefinition } from "../../types/field";

export const staffMatchEventLog: UIFieldDefinition[] = [
  {
    key: "match",
    filterKey: "match",
    label: "試合",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "team",
    filterKey: "team.team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "match_event_type",
    filterKey: "match_event_type.name",
    label: "イベントタイプ",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "staff",
    filterKey: "staff.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "time",
    label: "時間",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
  {
    key: "add_time",
    label: "追加タイム",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
  {
    key: "special_time",
    label: "特別タイム",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "period_label",
    label: "前後半",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "time_name",
    label: "時間",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "unique_key",
    label: "ユニークキー",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: false,
  },
];
