import { UIFieldDefinition } from "../../types/field";

export const staffRegistration: UIFieldDefinition[] = [
  {
    key: "date",
    label: "日付",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "season",
    filterKey: "season.name",
    label: "シーズン",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "competition",
    filterKey: "competition.name",
    label: "大会名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "staff",
    filterKey: "staff.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "team",
    filterKey: "team.team",
    label: "チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "role",
    label: "役割",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "name",
    label: "名前",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "en_name",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "registration_type",
    label: "登録・抹消",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "registration_status",
    label: "登録状況",
    type: "checkbox",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "note",
    label: "メモ",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
];
