import { FieldDefinition } from "../../types/field";

export const team: FieldDefinition[] = [
  {
    key: "team",
    label: "チーム名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "abbr",
    label: "略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "enTeam",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "country",
    label: "国名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "genre",
    label: "ジャンル",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "age_group",
    label: "年代",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "division",
    label: "2nd, 3rdなど",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "jdataid",
    label: "j.data.id",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
  {
    key: "labalph",
    label: "lab",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "transferurl",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "sofaurl",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
];
