import { UIFieldDefinition } from "../../types/field";
import { TeamGet } from "../../types/models/team";
import { ColumnType } from "../../types/table";

export const team: UIFieldDefinition<TeamGet>[] = [
  {
    key: "normalized_name",
    field: "normalized_name",
    label: "正規化チーム",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "team",
    field: "team",
    label: "チーム名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "abbr",
    field: "abbr",
    label: "略称",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "enTeam",
    field: "enTeam",
    label: "英名",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "country",
    field: "country",
    filterKey: "country.name",
    label: "国",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "genre",
    field: "genre",
    width: "100px",
    label: "ジャンル",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "age_group",
    field: "age_group",
    label: "年代",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "division",
    field: "division",
    label: "2nd, 3rdなど",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "jdataid",
    field: "jdataid",
    label: "j.data.id",
    type: "number",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "labalph",
    field: "labalph",
    label: "lab",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "transferurl",
    field: "transferurl",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "sofaurl",
    field: "sofaurl",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "old_id",
    field: "old_id",
    label: "旧ID",
    type: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
];
