import { UIFieldDefinition } from "../../types/field";
import { TransferGet } from "../../types/models/transfer";
import { ColumnType } from "../../types/table";

export const transfer: UIFieldDefinition<TransferGet>[] = [
  {
    key: "doa",
    field: "doa",
    label: "移籍発表日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "from_team",
    field: "from_team",
    filterKey: "from_team.team",
    label: "移籍元",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "to_team",
    field: "to_team",
    filterKey: "to_team.team",
    label: "移籍先",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "player",
    field: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "position",
    field: "position",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "form",
    field: "form",
    label: "移籍形態",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "number",
    field: "number",
    label: "背番号",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "from_date",
    field: "from_date",
    label: "新チーム加入日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "to_date",
    field: "to_date",
    label: "新チーム満了予定日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
    displayOnTable: true,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "URL",
    field: "URL",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
  {
    key: "isCancelled",
    field: "isCancelled",
    label: "キャンセル",
    type: "checkbox",
    filterable: true,
    sortable: false,
    displayOnDetail: true,
    displayOnTable: false,
    getValueType: ColumnType.FIELD,
  },
];
