import { UIFieldDefinition } from "../../types/field";

export const transfer: UIFieldDefinition[] = [
  {
    key: "doa",
    label: "移籍発表日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "from_team",
    filterKey: "from_team.team",
    label: "移籍元",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "to_team",
    filterKey: "to_team.team",
    label: "移籍先",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "player",
    filterKey: "player.name",
    label: "選手",
    type: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "position",
    label: "ポジション",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "form",
    label: "移籍形態",
    type: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "number",
    label: "背番号",
    type: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "from_date",
    label: "新チーム加入日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "to_date",
    label: "新チーム満了予定日",
    type: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "URL",
    label: "URL",
    type: "string",
    filterable: true,
    sortable: false,
    displayOnDetail: true,
  },
];
