import { FieldDefinition } from "../../types/field";

export const transfer: FieldDefinition[] = [
  {
    key: "doa",
    label: "移籍発表日",
    filterType: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "from_team",
    label: "移籍元",
    filterType: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "to_team",
    label: "移籍先",
    filterType: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "player",
    label: "選手",
    filterType: "string",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "position",
    label: "ポジション",
    filterType: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "form",
    label: "移籍形態",
    filterType: "select",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "number",
    label: "背番号",
    filterType: "number",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "from_date",
    label: "新チーム加入日",
    filterType: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "to_date",
    label: "新チーム満了予定日",
    filterType: "Date",
    filterable: true,
    sortable: true,
    displayOnDetail: true,
  },
  {
    key: "URL",
    label: "URL",
    filterType: "string",
    filterable: false,
    sortable: false,
    displayOnDetail: true,
  },
];
