// import { runControllerTests } from "./utils.ts/runControllerTests.ts";
// import { competitionStage } from "../../shared/dist/models-config/competition-stage.js";
// import { competition } from "../../shared/dist/models-config/competition.js";
// import { country } from "../../shared/dist/models-config/country.js";
// import { injury } from "../../shared/dist/models-config/injury.js";
// import { matchFormat } from "../../shared/dist/models-config/match-format.js";
// import { match } from "../../shared/dist/models-config/match.js";
// import { nationalCallUp } from "../../shared/dist/models-config/national-callup.js";
// import { nationalMatchSeries } from "../../shared/dist/models-config/national-match-series.js";
// import { player } from "../../shared/dist/models-config/player.js";
// import { PlayerModel } from "models/player.ts";
// import { referee } from "../../shared/dist/models-config/referee.js";
// import { season } from "../../shared/dist/models-config/season.js";
// import { stadium } from "../../shared/dist/models-config/stadium.js";
// import { teamCompetitionSeason } from "../../shared/dist/models-config/team-competition-season.js";
// import { team } from "../../shared/dist/models-config/team.js";
// import { transfer } from "../../shared/dist/models-config/transfer.js";

// runControllerTests(player(PlayerModel));
// runControllerTests(country);
// runControllerTests(referee);
// runControllerTests(team);
// runControllerTests(stadium);
// runControllerTests(injury);
// runControllerTests(nationalMatchSeries);
// runControllerTests(nationalCallUp);
// runControllerTests(competition);
// runControllerTests(season);
// runControllerTests(competitionStage);
// runControllerTests(matchFormat);
// runControllerTests(teamCompetitionSeason);
// runControllerTests(match);
// runControllerTests(transfer(TransferModel));
