import { runControllerTests } from "./utils.ts/runControllerTests.ts";
import { competitionStage } from "../../shared/models-config/competition-stage.ts";
import { competition } from "../../shared/models-config/competition.ts";
import { country } from "../../shared/models-config/country.ts";
import { injury } from "../../shared/models-config/injury.ts";
import { matchFormat } from "../../shared/models-config/match-format.ts";
import { match } from "../../shared/models-config/match.ts";
import { nationalCallUp } from "../../shared/models-config/national-callup.ts";
import { nationalMatchSeries } from "../../shared/models-config/national-match-series.ts";
import { player } from "../../shared/models-config/player.ts";
import { referee } from "../../shared/models-config/referee.ts";
import { season } from "../../shared/models-config/season.ts";
import { stadium } from "../../shared/models-config/stadium.ts";
import { teamCompetitionSeason } from "../../shared/models-config/team-competition-season.ts";
import { team } from "../../shared/models-config/team.ts";
import { transfer } from "../../shared/models-config/transfer.ts";

runControllerTests(player);
runControllerTests(country);
runControllerTests(referee);
runControllerTests(team);
runControllerTests(stadium);
runControllerTests(injury);
runControllerTests(nationalMatchSeries);
runControllerTests(nationalCallUp);
runControllerTests(competition);
runControllerTests(season);
runControllerTests(competitionStage);
runControllerTests(matchFormat);
runControllerTests(teamCompetitionSeason);
runControllerTests(match);
runControllerTests(transfer);
