export const result = {
  ok: true,
  url: "test",
  data: {
    match: {
      competition_stage: {
        name: "ＡＦＣチャンピオンズリーグエリート　ラウンド１６",
      },
      match_week: undefined,
      name:
        "ＡＦＣチャンピオンズリーグエリート　ラウンド１６　\n" +
        "                    2026年3月3日（火）19:01KO\n" +
        "                    春川松岩スポーツタウン・スタジアム",
      date: new Date("2026-03-03T10:01:00.000Z"),
      stadium: { name: "春川松岩スポーツタウン・スタジアム" },
      stadium_name: "春川松岩スポーツタウン・スタジアム",
      home_goal: 0,
      away_goal: 0,
      home_pk_goal: undefined,
      away_pk_goal: undefined,
      home_team: { abbr: "江原", team: "江原FC" },
      away_team: { abbr: "町田", team: "FC町田ゼルビア" },
      match_format: { name: "90" },
      audience: undefined,
      weather: "曇り",
      temperature: 5,
      humidity: 62,
      urls: ["test"],
    },

    playerAppearance: {
      home: [
        {
          number: 21,
          player_name: "パク　チョンヒョ",
          play_status: "start",
          player: { name: "パク　チョンヒョ" },
          start_time: 0,
          end_time: undefined,
          key: "21-パク　チョンヒョ",
        },
        {
          number: 13,
          player_name: "イ　ギヒョク",
          play_status: "start",
          player: { name: "イ　ギヒョク" },
          start_time: 0,
          end_time: undefined,
          key: "13-イ　ギヒョク",
        },
        {
          number: 24,
          player_name: "パク　ホヨン",
          play_status: "start",
          player: { name: "パク　ホヨン" },
          start_time: 0,
          end_time: undefined,
          key: "24-パク　ホヨン",
        },
        {
          number: 34,
          player_name: "ソン　ジュンソク",
          play_status: "start",
          player: { name: "ソン　ジュンソク" },
          start_time: 0,
          end_time: 81,
          key: "34-ソン　ジュンソク",
        },
        {
          number: 47,
          player_name: "シン　ミンハ",
          play_status: "start",
          player: { name: "シン　ミンハ" },
          start_time: 0,
          end_time: undefined,
          key: "47-シン　ミンハ",
        },
        {
          number: 99,
          player_name: "カン　ジュンヒョク",
          play_status: "start",
          player: { name: "カン　ジュンヒョク" },
          start_time: 0,
          end_time: undefined,
          key: "99-カン　ジュンヒョク",
        },
        {
          number: 4,
          player_name: "ソ　ミヌ",
          play_status: "start",
          player: { name: "ソ　ミヌ" },
          start_time: 0,
          end_time: 81,
          key: "4-ソ　ミヌ",
        },
        {
          number: 11,
          player_name: "コ　ヨンジュン",
          play_status: "start",
          player: { name: "コ　ヨンジュン" },
          start_time: 0,
          end_time: 71,
          key: "11-コ　ヨンジュン",
        },
        {
          number: 28,
          player_name: "イ　スンウォン",
          play_status: "start",
          player: { name: "イ　スンウォン" },
          start_time: 0,
          end_time: undefined,
          key: "28-イ　スンウォン",
        },
        {
          number: 19,
          player_name: "パク　サンヒョク",
          play_status: "start",
          player: { name: "パク　サンヒョク" },
          start_time: 0,
          end_time: 60,
          key: "19-パク　サンヒョク",
        },
        {
          number: 42,
          player_name: "モ　ジェヒョン",
          play_status: "start",
          player: { name: "モ　ジェヒョン" },
          start_time: 0,
          end_time: 71,
          key: "42-モ　ジェヒョン",
        },
        {
          number: 91,
          player_name: "キム　ジョンフン",
          play_status: "bench",
          player: { name: "キム　ジョンフン" },
          start_time: undefined,
          end_time: undefined,
          key: "91-キム　ジョンフン",
        },
        {
          number: 20,
          player_name: "チョ　ヒョンテ",
          play_status: "bench",
          player: { name: "チョ　ヒョンテ" },
          start_time: undefined,
          end_time: undefined,
          key: "20-チョ　ヒョンテ",
        },
        {
          number: 23,
          player_name: "マルコ　トゥチ",
          play_status: "bench",
          player: { name: "マルコ　トゥチ" },
          start_time: undefined,
          end_time: undefined,
          key: "23-マルコ　トゥチ",
        },
        {
          number: 25,
          player_name: "イ　ヒョビン",
          play_status: "bench",
          player: { name: "イ　ヒョビン" },
          start_time: undefined,
          end_time: undefined,
          key: "25-イ　ヒョビン",
        },
        {
          number: 8,
          player_name: "カン　ユング",
          play_status: "sub",
          player: { name: "カン　ユング" },
          start_time: 71,
          end_time: undefined,
          key: "8-カン　ユング",
        },
        {
          number: 97,
          player_name: "イ　ユヒョン",
          play_status: "sub",
          player: { name: "イ　ユヒョン" },
          start_time: 81,
          end_time: undefined,
          key: "97-イ　ユヒョン",
        },
        {
          number: 27,
          player_name: "キム　ドヒョン",
          play_status: "sub",
          player: { name: "キム　ドヒョン" },
          start_time: 81,
          end_time: undefined,
          key: "27-キム　ドヒョン",
        },
        {
          number: 39,
          player_name: "イ　ジホ",
          play_status: "bench",
          player: { name: "イ　ジホ" },
          start_time: undefined,
          end_time: undefined,
          key: "39-イ　ジホ",
        },
        {
          number: 50,
          player_name: "イ　ウンホ",
          play_status: "bench",
          player: { name: "イ　ウンホ" },
          start_time: undefined,
          end_time: undefined,
          key: "50-イ　ウンホ",
        },
        {
          number: 7,
          player_name: "キム　テウォン",
          play_status: "sub",
          player: { name: "キム　テウォン" },
          start_time: 71,
          end_time: undefined,
          key: "7-キム　テウォン",
        },
        {
          number: 80,
          player_name: "アブダラ　ハライハル",
          play_status: "sub",
          player: { name: "アブダラ　ハライハル" },
          start_time: 60,
          end_time: undefined,
          key: "80-アブダラ　ハライハル",
        },
        {
          number: 96,
          player_name: "チョ　ビョンチャン",
          play_status: "bench",
          player: { name: "チョ　ビョンチャン" },
          start_time: undefined,
          end_time: undefined,
          key: "96-チョ　ビョンチャン",
        },
      ],
      away: [
        {
          number: 1,
          player_name: "谷　晃生",
          play_status: "start",
          player: { name: "谷　晃生" },
          start_time: 0,
          end_time: undefined,
          key: "1-谷　晃生",
        },
        {
          number: 3,
          player_name: "昌子　源",
          play_status: "start",
          player: { name: "昌子　源" },
          start_time: 0,
          end_time: undefined,
          key: "3-昌子　源",
        },
        {
          number: 6,
          player_name: "望月　ヘンリー海輝",
          play_status: "start",
          player: { name: "望月　ヘンリー海輝" },
          start_time: 0,
          end_time: undefined,
          key: "6-望月　ヘンリー海輝",
        },
        {
          number: 19,
          player_name: "中山　雄太",
          play_status: "start",
          player: { name: "中山　雄太" },
          start_time: 0,
          end_time: undefined,
          key: "19-中山　雄太",
        },
        {
          number: 50,
          player_name: "岡村　大八",
          play_status: "start",
          player: { name: "岡村　大八" },
          start_time: 0,
          end_time: undefined,
          key: "50-岡村　大八",
        },
        {
          number: 16,
          player_name: "前　寛之",
          play_status: "start",
          player: { name: "前　寛之" },
          start_time: 0,
          end_time: undefined,
          key: "16-前　寛之",
        },
        {
          number: 18,
          player_name: "下田　北斗",
          play_status: "start",
          player: { name: "下田　北斗" },
          start_time: 0,
          end_time: 86,
          key: "18-下田　北斗",
        },
        {
          number: 88,
          player_name: "中村　帆高",
          play_status: "start",
          player: { name: "中村　帆高" },
          start_time: 0,
          end_time: 86,
          key: "88-中村　帆高",
        },
        {
          number: 7,
          player_name: "相馬　勇紀",
          play_status: "start",
          player: { name: "相馬　勇紀" },
          start_time: 0,
          end_time: 90,
          key: "7-相馬　勇紀",
        },
        {
          number: 10,
          player_name: "ナ　サンホ",
          play_status: "start",
          player: { name: "ナ　サンホ" },
          start_time: 0,
          end_time: 59,
          key: "10-ナ　サンホ",
        },
        {
          number: 99,
          player_name: "テテ　イェンギ",
          play_status: "start",
          player: { name: "テテ　イェンギ" },
          start_time: 0,
          end_time: 59,
          key: "99-テテ　イェンギ",
        },
        {
          number: 13,
          player_name: "守田　達弥",
          play_status: "bench",
          player: { name: "守田　達弥" },
          start_time: undefined,
          end_time: undefined,
          key: "13-守田　達弥",
        },
        {
          number: 44,
          player_name: "新井　栄聡",
          play_status: "bench",
          player: { name: "新井　栄聡" },
          start_time: undefined,
          end_time: undefined,
          key: "44-新井　栄聡",
        },
        {
          number: 26,
          player_name: "林　幸多郎",
          play_status: "sub",
          player: { name: "林　幸多郎" },
          start_time: 86,
          end_time: undefined,
          key: "26-林　幸多郎",
        },
        {
          number: 5,
          player_name: "ドレシェヴィッチ",
          play_status: "bench",
          player: { name: "ドレシェヴィッチ" },
          start_time: undefined,
          end_time: undefined,
          key: "5-ドレシェヴィッチ",
        },
        {
          number: 23,
          player_name: "白崎　凌兵",
          play_status: "bench",
          player: { name: "白崎　凌兵" },
          start_time: undefined,
          end_time: undefined,
          key: "23-白崎　凌兵",
        },
        {
          number: 31,
          player_name: "ネタ　ラヴィ",
          play_status: "sub",
          player: { name: "ネタ　ラヴィ" },
          start_time: 86,
          end_time: undefined,
          key: "31-ネタ　ラヴィ",
        },
        {
          number: 34,
          player_name: "徳村　楓大",
          play_status: "bench",
          player: { name: "徳村　楓大" },
          start_time: undefined,
          end_time: undefined,
          key: "34-徳村　楓大",
        },
        {
          number: 8,
          player_name: "仙頭　啓矢",
          play_status: "bench",
          player: { name: "仙頭　啓矢" },
          start_time: undefined,
          end_time: undefined,
          key: "8-仙頭　啓矢",
        },
        {
          number: 11,
          player_name: "増山　朝陽",
          play_status: "bench",
          player: { name: "増山　朝陽" },
          start_time: undefined,
          end_time: undefined,
          key: "11-増山　朝陽",
        },
        {
          number: 20,
          player_name: "西村　拓真",
          play_status: "sub",
          player: { name: "西村　拓真" },
          start_time: 59,
          end_time: undefined,
          key: "20-西村　拓真",
        },
        {
          number: 49,
          player_name: "桑山　侃士",
          play_status: "sub",
          player: { name: "桑山　侃士" },
          start_time: 90,
          end_time: 1,
          key: "49-桑山　侃士",
        },
        {
          number: 9,
          player_name: "藤尾　翔太",
          play_status: "sub",
          player: { name: "藤尾　翔太" },
          start_time: 59,
          end_time: undefined,
          key: "9-藤尾　翔太",
        },
      ],
    },
    playerMatchEventLog: {
      home: [
        {
          player: { name: "ソ　ミヌ", number: 4 },
          player_name: "ソ　ミヌ",
          time: 31,
          add_time: undefined,
          time_name: "31",
          match_event_type: { name: "警告" },
          special_time: undefined,
          key: "4-ソ　ミヌ",
        },
        {
          player: { name: "モ　ジェヒョン", number: 42 },
          player_name: "モ　ジェヒョン",
          time: 52,
          add_time: undefined,
          time_name: "52",
          match_event_type: { name: "警告" },
          special_time: undefined,
          key: "42-モ　ジェヒョン",
        },
        {
          player: { name: "パク　サンヒョク", number: 19 },
          player_name: "パク　サンヒョク",
          time: 60,
          add_time: undefined,
          time_name: "60",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "19-パク　サンヒョク",
        },
        {
          player: { name: "アブダラ　ハライハル", number: 80 },
          player_name: "アブダラ　ハライハル",
          time: 60,
          add_time: undefined,
          time_name: "60",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "80-アブダラ　ハライハル",
        },
        {
          player: { name: "コ　ヨンジュン", number: 11 },
          player_name: "コ　ヨンジュン",
          time: 71,
          add_time: undefined,
          time_name: "71",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "11-コ　ヨンジュン",
        },
        {
          player: { name: "キム　テウォン", number: 7 },
          player_name: "キム　テウォン",
          time: 71,
          add_time: undefined,
          time_name: "71",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "7-キム　テウォン",
        },
        {
          player: { name: "モ　ジェヒョン", number: 42 },
          player_name: "モ　ジェヒョン",
          time: 71,
          add_time: undefined,
          time_name: "71",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "42-モ　ジェヒョン",
        },
        {
          player: { name: "カン　ユング", number: 8 },
          player_name: "カン　ユング",
          time: 71,
          add_time: undefined,
          time_name: "71",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "8-カン　ユング",
        },
        {
          player: { name: "ソ　ミヌ", number: 4 },
          player_name: "ソ　ミヌ",
          time: 81,
          add_time: undefined,
          time_name: "81",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "4-ソ　ミヌ",
        },
        {
          player: { name: "イ　ユヒョン", number: 97 },
          player_name: "イ　ユヒョン",
          time: 81,
          add_time: undefined,
          time_name: "81",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "97-イ　ユヒョン",
        },
        {
          player: { name: "ソン　ジュンソク", number: 34 },
          player_name: "ソン　ジュンソク",
          time: 81,
          add_time: undefined,
          time_name: "81",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "34-ソン　ジュンソク",
        },
        {
          player: { name: "キム　ドヒョン", number: 27 },
          player_name: "キム　ドヒョン",
          time: 81,
          add_time: undefined,
          time_name: "81",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "27-キム　ドヒョン",
        },
      ],
      away: [
        {
          player: { name: "中村　帆高", number: 88 },
          player_name: "中村　帆高",
          time: 24,
          add_time: undefined,
          time_name: "24",
          match_event_type: { name: "警告" },
          special_time: undefined,
          key: "88-中村　帆高",
        },
        {
          player: { name: "ナ　サンホ", number: 10 },
          player_name: "ナ　サンホ",
          time: 59,
          add_time: undefined,
          time_name: "59",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "10-ナ　サンホ",
        },
        {
          player: { name: "西村　拓真", number: 20 },
          player_name: "西村　拓真",
          time: 59,
          add_time: undefined,
          time_name: "59",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "20-西村　拓真",
        },
        {
          player: { name: "テテ　イェンギ", number: 99 },
          player_name: "テテ　イェンギ",
          time: 59,
          add_time: undefined,
          time_name: "59",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "99-テテ　イェンギ",
        },
        {
          player: { name: "藤尾　翔太", number: 9 },
          player_name: "藤尾　翔太",
          time: 59,
          add_time: undefined,
          time_name: "59",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "9-藤尾　翔太",
        },
        {
          player: { name: "下田　北斗", number: 18 },
          player_name: "下田　北斗",
          time: 86,
          add_time: undefined,
          time_name: "86",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "18-下田　北斗",
        },
        {
          player: { name: "ネタ　ラヴィ", number: 31 },
          player_name: "ネタ　ラヴィ",
          time: 86,
          add_time: undefined,
          time_name: "86",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "31-ネタ　ラヴィ",
        },
        {
          player: { name: "中村　帆高", number: 88 },
          player_name: "中村　帆高",
          time: 86,
          add_time: undefined,
          time_name: "86",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "88-中村　帆高",
        },
        {
          player: { name: "林　幸多郎", number: 26 },
          player_name: "林　幸多郎",
          time: 86,
          add_time: undefined,
          time_name: "86",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "26-林　幸多郎",
        },
        {
          player: { name: "相馬　勇紀", number: 7 },
          player_name: "相馬　勇紀",
          time: 90,
          add_time: 1,
          time_name: "90+1",
          match_event_type: { name: "途中交代" },
          special_time: undefined,
          key: "7-相馬　勇紀",
        },
        {
          player: { name: "桑山　侃士", number: 49 },
          player_name: "桑山　侃士",
          time: 90,
          add_time: 1,
          time_name: "90+1",
          match_event_type: { name: "途中出場" },
          special_time: undefined,
          key: "49-桑山　侃士",
        },
      ],
    },
    refereeAppearance: [
      { referee: { name: "アブドゥル　ハシム" }, role: "REFEREE" },
      { referee: { name: "マノジ　カルワニ" }, role: "ASSISTANT_REFEREE" },
      {
        referee: { name: "アショクライ　ジェーヴァラハ" },
        role: "ASSISTANT_REFEREE",
      },
      {
        referee: { name: "ムハンマド　ナズミ　ナサルディン" },
        role: "FOURTH_OFFICIAL",
      },
      { referee: { name: "ウィワット　ジャンポーン" }, role: "VAR" },
      { referee: { name: "タン　ピンファン" }, role: "AVAR" },
    ],
    staffAppearance: {
      home: [
        {
          staff_name: "チョン　ギョンホ",
          staff: { name: "チョン　ギョンホ" },
          role: "MANAGER",
        },
      ],
      away: [
        {
          staff_name: "黒田　剛",
          staff: { name: "黒田　剛" },
          role: "MANAGER",
        },
      ],
    },
  },
};
